version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: verifast
      POSTGRES_PASSWORD: verifast123
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6380:6379"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"  # Qdrant REST API
      - "6334:6334"  # gRPC API (optional)
    volumes:
      - qdrant_data:/qdrant/storage

  backend:
    build: .
    container_name: rag-news-backend
    depends_on:
      - db
      - redis
      - qdrant
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app

volumes:
  pgdata:
  qdrant_data:
